#!/usr/bin/env bash

# Copyright (C) 2023 Thomas Weißschuh <thomas@t-8ch.de>
#
# This file is part of util-linux.
#
# This file is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This file is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

TS_TOPDIR="${0%/*}/../.."
TS_DESC="lsclocks"

. "$TS_TOPDIR"/functions.sh
ts_init "$*"

ts_check_test_command "$TS_CMD_LSCLOCKS"
ts_check_prog sed 

mask_timestamps() {
	sed 's/[0-9]\+\.[0-9]\+/X.X/g'
}

NO_DISCOVER="--no-discover-dynamic --no-discover-rtc"

ts_init_subtest basic

"$TS_CMD_LSCLOCKS" $NO_DISCOVER --output TYPE,ID,CLOCK,NAME | grep -v CLOCK_AUX \
	> "$TS_OUTPUT" 2>> "$TS_ERRLOG"

ts_finalize_subtest

ts_init_subtest time

"$TS_CMD_LSCLOCKS" --time monotonic | mask_timestamps > "$TS_OUTPUT" 2>> "$TS_ERRLOG"

ts_finalize_subtest

ts_init_subtest dynamic

if [ -c /dev/ptp0 ] && [ -r /dev/ptp0 ]; then
	"$TS_CMD_LSCLOCKS" $NO_DISCOVER --dynamic-clock /dev/ptp0 --output TYPE,ID,CLOCK,NAME \
		| tail -1 > "$TS_OUTPUT" 2>> "$TS_ERRLOG"
else
	ts_skip "/dev/ptp0 not usable"
fi
ts_finalize_subtest

ts_init_subtest rtc

if [ -c /dev/rtc0 ] && [ -r /dev/rtc0 ]; then
	"$TS_CMD_LSCLOCKS" $NO_DISCOVER --rtc /dev/rtc0 --output TYPE,ID,CLOCK,NAME \
		| tail -1 > "$TS_OUTPUT" 2>> "$TS_ERRLOG"

	if ! rtc_time_utc=$(TZ=UTC0 "$TS_CMD_LSCLOCKS" $NO_DISCOVER --rtc /dev/rtc0 \
			--noheadings --raw --output TIME 2>> "$TS_ERRLOG"); then
		ts_failed "could not read /dev/rtc0 in UTC"
	elif ! rtc_time_offset=$(TZ=UTC+11 "$TS_CMD_LSCLOCKS" $NO_DISCOVER --rtc /dev/rtc0 \
			--noheadings --raw --output TIME 2>> "$TS_ERRLOG"); then
		ts_failed "could not read /dev/rtc0 with fixed timezone offset"
	else
		rtc_time_utc=${rtc_time_utc##*$'\n'}
		rtc_time_offset=${rtc_time_offset##*$'\n'}
		if [[ ! "$rtc_time_utc" =~ ^[0-9]+\.[0-9]{9}$ ]] ||
		   [[ ! "$rtc_time_offset" =~ ^[0-9]+\.[0-9]{9}$ ]]; then
			ts_failed "invalid RTC timestamps: $rtc_time_utc $rtc_time_offset"
		else
			rtc_time_utc=${rtc_time_utc%%.*}
			rtc_time_offset=${rtc_time_offset%%.*}
			rtc_drift=$((rtc_time_offset - rtc_time_utc))
			if [ "$rtc_drift" -lt 0 ]; then
				ts_failed "RTC timestamp moved backwards by $((-rtc_drift)) seconds"
			elif [ "$rtc_drift" -gt 2 ]; then
				ts_failed "RTC timestamp drifted by $rtc_drift seconds"
			fi
		fi
	fi
else
	ts_skip "/dev/rtc0 not usable"
fi
ts_finalize_subtest

ts_init_subtest cpu

"$TS_CMD_LSCLOCKS" --cpu 1 --output TYPE,ID,NAME | tail -1 > "$TS_OUTPUT" 2>> "$TS_ERRLOG"

ts_finalize_subtest

ts_finalize
